# Generated by Django 3.1.4 on 2021-01-18 06:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbal', '0002_followers_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
