# Generated by Django 3.1.4 on 2021-01-18 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('birbal', '0003_questions_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('answerFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_for', to='birbal.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
