# Generated by Django 3.1.4 on 2021-01-20 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birbal', '0005_answers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='useful',
            field=models.ManyToManyField(related_name='useful_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
